version: '3.5'
services:
  ######################################################
  # DataGenerator
  ######################################################

  Invoices:
    image: generator:latest
    profiles:
      - Invoices
    restart: no
    container_name: Invoices
    volumes:
      - ${PROJECT_BASE_DIR:-.}/generated-files:/root/generated-files
      - ${PROJECT_BASE_DIR:-.}/config/data_generator.conf:/root/config/data_generator.conf
    command: Invoices
    network_mode: host

  Payments:
    image: generator:latest
    profiles:
      - Payments
    restart: no
    container_name: Payments
    volumes:
      - ${PROJECT_BASE_DIR:-.}/generated-files:/root/generated-files
      - ${PROJECT_BASE_DIR:-.}/config/data_generator.conf:/root/config/data_generator.conf
    command: Payments
    network_mode: host

  PaymentsMaster:
    image: generator:latest
    profiles:
      - PaymentsMaster
    restart: no
    container_name: PaymentsMaster
    volumes:
      - ${PROJECT_BASE_DIR:-.}/generated-files:/root/generated-files
      - ${PROJECT_BASE_DIR:-.}/config/data_generator.conf:/root/config/data_generator.conf
    command: PaymentsMaster
    network_mode: host


