version: '3.5'
services:
  ######################################################
  # DataGenerator
  ######################################################

  customers-file:
    image: generator:latest
    profiles:
      - customers-file
    restart: no
    container_name: customers-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: customers

  customers-kafka:
    image: generator:latest
    profiles:
      - customers-kafka
    restart: no
    container_name: customers-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=customers-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: customers
    network_mode: host

  products-file:
    image: generator:latest
    profiles:
      - products-file
    restart: no
    container_name: products-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: products

  products-kafka:
    image: generator:latest
    profiles:
      - products-kafka
    restart: no
    container_name: products-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=products-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: products
    network_mode: host

  stores-file:
    image: generator:latest
    profiles:
      - stores-file
    restart: no
    container_name: stores-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: stores

  stores-kafka:
    image: generator:latest
    profiles:
      - stores-kafka
    restart: no
    container_name: stores-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=stores-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: stores
    network_mode: host
  ######################################################
  # In case of orders and payment,
  # All other files like customer,product, stores will be recreated to give joining records with orders and payment
  # If you choose to write to file, all data will be written to file only.
  # If you choose to write to kafka, customer, product, stores will be written to file
  # as well as kafka but orders/payment will be written to kafka only.
  ######################################################
  orders-file:
    image: generator:latest
    profiles:
      - orders-file
    restart: no
    container_name: orders-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: orders

  orders-kafka:
    image: generator:latest
    profiles:
      - orders-kafka
    restart: no
    container_name: orders-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=orders-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: orders
    network_mode: host

  payments-file:
    image: generator:latest
    profiles:
      - payments-file
    restart: no
    container_name: payments-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: payments

  payments-kafka:
    image: generator:latest
    profiles:
      - payments-kafka
    restart: no
    container_name: payments-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=payments-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: payments
    network_mode: host

