version: '3.5'
services:
  ######################################################
  # DataGenerator
  ######################################################

  customers-file:
    image: generator:latest
    profiles:
      - customer-file
    restart: no
    container_name: customer-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: customer

  customers-kafka:
    image: generator:latest
    profiles:
      - customer-kafka
    restart: no
    container_name: customer-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=customer-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: customer
    network_mode: host

  products-file:
    image: generator:latest
    profiles:
      - product-file
    restart: no
    container_name: product-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: product

  products-kafka:
    image: generator:latest
    profiles:
      - product-kafka
    restart: no
    container_name: product-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=product-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: product
    network_mode: host

  stores-file:
    image: generator:latest
    profiles:
      - store-file
    restart: no
    container_name: store-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: store

  stores-kafka:
    image: generator:latest
    profiles:
      - store-kafka
    restart: no
    container_name: store-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=store-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: store
    network_mode: host
  ######################################################
  # In case of orders and payment,
  # All other files like customer,product, store will be recreated to give joining records with orders and payment
  # If you choose to write to file, all data will be written to file only.
  # If you choose to write to kafka, customer, product, store will be written to file
  # as well as kafka but orders/payment will be written to kafka only.
  ######################################################
  orders-file:
    image: generator:latest
    profiles:
      - orders-file
    restart: no
    container_name: orders-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: orders

  orders-kafka:
    image: generator:latest
    profiles:
      - orders-kafka
    restart: no
    container_name: orders-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=orders-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: orders
    network_mode: host

  payments-file:
    image: generator:latest
    profiles:
      - payments-file
    restart: no
    container_name: payments-file
    volumes:
      - ./generated-files:/root/generated-files
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=100
      - TARGET_TYPE=file
      - OUTPUT_DATA_FORMAT=json
      - PRINT_DATA_ON_CONSOLE=false
    command: payments

  payments-kafka:
    image: generator:latest
    profiles:
      - payments-kafka
    restart: no
    container_name: payments-kafka
    environment:
      - NUMBER_OF_MESSAGES_TO_PUBLISH=10
      - TARGET_TYPE=kafka
      - OUTPUT_DATA_FORMAT=avro
      - PRINT_DATA_ON_CONSOLE=true
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_TOPIC=payments-avro
      - ZOOKEEPER=127.0.0.1:2181
      - SCHEMA_REGISTRY_URL=http://127.0.0.1:18081
    command: payments
    network_mode: host

